/**
 * Removes "model" from required[] in each branch of a discriminated-union JSON Schema
 * (oneOf/anyOf), so MCP clients treat `model` as optional.
 *
 * The runtime z.preprocess injects model="gpt-image-2" when omitted, but the JSON Schema
 * generated by zod-to-json-schema marks model as required in each branch. This helper
 * reconciles the two views.
 */
export const withOptionalModel = (
  schema: Record<string, unknown>,
): Record<string, unknown> => {
  const branches = (schema.anyOf ?? schema.oneOf) as
    | Record<string, unknown>[]
    | undefined;
  if (!Array.isArray(branches)) {
    return schema;
  }

  const fixedBranches = branches.map((branch) => {
    const required = branch.required;
    if (!Array.isArray(required)) {
      return branch;
    }
    return {
      ...branch,
      required: required.filter((field) => field !== "model"),
    };
  });

  const key = schema.anyOf !== undefined ? "anyOf" : "oneOf";
  return { ...schema, [key]: fixedBranches };
};
